POST http://localhost:8080/user/create_account_admin HTTP/1.1
Content-Type: application/json

{
    "userId": 0,
    "firstName": "Nick",
    "lastName": "Dorsett",
    "email": "ndorsett@dev-10.com",
    "password": "pa55word!"
}

###
POST http://localhost:8080/user/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "ndorsett@dev-10.com",
    "password": "pa55word!"
}

###

POST http://localhost:8080/user/create_account_admin HTTP/1.1
Content-Type: application/json

{
    "userId": 0,
    "firstName": "Jamie",
    "lastName": "Lepito",
    "email": "jlepito@dev-10.com",
    "password": "pa66word!"
}

###

POST http://localhost:8080/user/create_account_admin HTTP/1.1
Content-Type: application/json

{
    "userId": 0,
    "firstName": "Cecilia",
    "lastName": "Barkume",
    "email": "cbarkume@dev-10.com",
    "password": "pa77word!"
}

###
GET `http://localhost:8080/recipe/healthInfo/1` HTTP/1.1

###

GET http://localhost:8080/recipe/healthInfo/1 HTTP/1.1
